type
	MwDIRECTION = (MwNORTH := 0, MwSOUTH, MwEAST, MwWEST);
	MwORIENTATION = (MwVERTICAL := 0, MwHORIZONTAL);
	MwALIGNMENT = (MwALIGNMENT_CENTER := 0, MwALIGNMENT_BEGINNING, MwALIGNMENT_END);
	MwMB_ICON = (MwMB_ICONWARNING := $1, MwMB_ICONINFO, MwMB_ICONNOTE, MwMB_ICONQUESTION, MwMB_ICONNEWS, MwMB_ICONERROR, MwMB_ICONCLOCK);
	MwClipboardType = (MwClipboardMain := 0, MwClipboardPrimary);
	MwVulkanField = (MwVulkanField_GetInstanceProcAddr := 0, MwVulkanField_Instance, MwVulkanField_Surface, MwVulkanField_PhysicalDevice, MwVulkanField_LogicalDevice, MwVulkanField_GraphicsQueueIndex, MwVulkanField_PresentQueueIndex, MwVulkanField_GraphicsQueue, MwVulkanField_PresentQueue);
