var
	MwButtonClass : Pointer; external name 'MwButtonClass';
	MwCheckBoxClass : Pointer; external name 'MwCheckBoxClass';
	MwEntryClass : Pointer; external name 'MwEntryClass';
	MwFrameClass : Pointer; external name 'MwFrameClass';
	MwImageClass : Pointer; external name 'MwImageClass';
	MwLabelClass : Pointer; external name 'MwLabelClass';
	MwListBoxClass : Pointer; external name 'MwListBoxClass';
	MwMenuClass : Pointer; external name 'MwMenuClass';
	MwNumberEntryClass : Pointer; external name 'MwNumberEntryClass';
	MwOpenGLClass : Pointer; external name 'MwOpenGLClass';
	MwScrollBarClass : Pointer; external name 'MwScrollBarClass';
	MwSubMenuClass : Pointer; external name 'MwSubMenuClass';
	MwViewportClass : Pointer; external name 'MwViewportClass';
	MwWindowClass : Pointer; external name 'MwWindowClass';
